// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjKMvqJKmVKAxBJ_zsYD5OPjpVdmiZgGQ',
    appId: '1:178007127464:web:8ea33a97876bb7ef68999d',
    messagingSenderId: '178007127464',
    projectId: 'ossp2-pickme-6',
    authDomain: 'ossp2-pickme-6.firebaseapp.com',
    storageBucket: 'ossp2-pickme-6.appspot.com',
    measurementId: 'G-70249NQ834',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Yr6da4f4FddMJNSwbHmwNVhWJs21fnw',
    appId: '1:178007127464:android:fdb0376f3ff5d82968999d',
    messagingSenderId: '178007127464',
    projectId: 'ossp2-pickme-6',
    storageBucket: 'ossp2-pickme-6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArSTIiaFIniC6va-_8MfvzITL1nASPtAs',
    appId: '1:178007127464:ios:69f00b215ee638fc68999d',
    messagingSenderId: '178007127464',
    projectId: 'ossp2-pickme-6',
    storageBucket: 'ossp2-pickme-6.appspot.com',
    iosBundleId: 'com.example.osspPickme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArSTIiaFIniC6va-_8MfvzITL1nASPtAs',
    appId: '1:178007127464:ios:7bf8050fd790eb4068999d',
    messagingSenderId: '178007127464',
    projectId: 'ossp2-pickme-6',
    storageBucket: 'ossp2-pickme-6.appspot.com',
    iosBundleId: 'com.example.osspPickme.RunnerTests',
  );
}
